[package]
name = "crates"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "A fun game where you guess what number the computer has chosen"

[dependencies]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[workspace]
members = [
    "adder",
    "add_one"
]